### ISSUE TITLE
How to setup this extension?

### ISSUE THREAD

**Issue by xiaobuxun** [bizley/yii2-podium#50]
Hi Bizley,

I am a new for Yii, I want to setup a forum use your Yii2-podium, so first I install the advance template form Yii2, and then I follow the step from you to install Yii2-podium, and it is a extension and go into "vendor". Question is this step I don't know how I can do:

```
> Go to the podium/install url of your application.
> Click Start Podium Installation button.
> 
> Podium will create all database tables and prepare administrator account.
```

I am thinking is, shoud I copy the files from "vendor" to my application basepath to make a new application, right?

Anyhelp? 

Thanks!

**Comment by bizley** [comment]
Are you using composer for installation? I hope so, it's so much easier this way.

Installation in case of advanced template is practically the same as for the basic one. You need to modify `/frontend/config/main.php` (or `backend` if you want Podium to run there instead) and `console/config/main.php` for mail queue.

Next step is to go to the URL where `frontend` is pointed to and add `podium/install` to the address.

You don't have to copy anything from the `vendor` folder.

**Comment by xiaobuxun** [comment]
Hi,

Thanks for your answer, but I still don't finish set up.

I use composer for installation.

Mine frontend/config/main.php like this:

```
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-frontend',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'podium'],
    'controllerNamespace' => 'frontend\controllers',
    'modules' => [
        'podium' => [
            'class' => 'bizley\podium\Module',
            //'allowedIPs' => ['xxx.xxx.xxx.xxx'], // optional
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-frontend',
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-frontend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        /*
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        */
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1;dbname=test',
            'username' => 'root',
            'password' => 'rootroot',
            'charset' => 'utf8',
        ],
    ],
    'params' => $params,

];
```

And onsole/config/main.php:

```
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'console\controllers',
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1;dbname=sophon',
            'username' => 'root',
            'password' => 'rootroot',
            'charset' => 'utf8',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'SMTP host',
                'username' => 'SMTP username',
                'password' => 'SMTP password',
                'port' => 'SMTP port', // optional
                'encryption' => 'SMTP encryption', // optional
            ],
        ],
    ],
    'params' => $params,
];
```

And mine frontend URL is "localhost/test/frontend/web/", then I add "podium/install" behind this URL,
"localhost/test/frontend/web/podium/install". But still can't found page(404).

What should I change also? Is it because I don't have a mail server?

Thanks!

**Comment by bizley** [comment]
Looks like your URL should be

```
localhost/test/frontend/web/index.php?r=podium/install
```

**Comment by xiaobuxun** [comment]
Hi,

Sorry, I try use this link, but it still 404 error.
I use this link:
`http://localhost/test/frontend/web/index.php?r=podium/install`
I don't how to do.

**Comment by bizley** [comment]
Right, sorry, it should be more like

```
http://localhost/test/frontend/web/index.php?r=podium/install/run
```

First link works in case of configured UrlManager.

**Comment by xiaobuxun** [comment]
Hi,

Thanks many much! Use the URl, I open the install page!

Unfortunately, it is have a error when I install.

`There was a major error during installation! Check your runtime log for details.`

And here is what I found in log field.

```
2016-10-27 11:02:12 [127.0.0.1][-][8j8qvvq1jq3f0suupvnhj53va2][error][yii\base\ErrorException:64] yii\base\ErrorException: Access level to Zelenin\yii\behaviors\Slug::validateSlug() must be protected (as in class yii\behaviors\SluggableBehavior) or weaker in D:\localweb\www\sophon\vendor\zelenin\yii2-slug-behavior\Slug.php:13
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

```

Thanks!

**Comment by bizley** [comment]
Either run in the console `composer update` on the project again to fetch newer version of `zelenin/yii2-slug-behavior` or (if this doesn't work) run `composer require zelenin/yii2-slug-behavior "~1.5.1"`

**Comment by xiaobuxun** [comment]
Hi,

I run `composer require zelenin/yii2-slug-behavior "~1.5.1"` to update zelenin.

And I reinstall this extension, I got this error:

```
2016-10-27 16:25:16 [127.0.0.1][-][8j8qvvq1jq3f0suupvnhj53va2][error][Error] Error: Call to undefined method RuntimeException::getName() in D:\localweb\www\test\vendor\bizley\podium\src\maintenance\Installation.php:71
Stack trace:
#0 [internal function]: bizley\podium\maintenance\Installation->addAdmin(Array)
#1 D:\localweb\www\test\vendor\bizley\podium\src\maintenance\Installation.php(265): call_user_func(Array, Array)
#2 D:\localweb\www\test\vendor\bizley\podium\src\controllers\InstallController.php(80): bizley\podium\maintenance\Installation->nextStep()
#3 [internal function]: bizley\podium\controllers\InstallController->actionImport()
#4 D:\localweb\www\test\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#5 D:\localweb\www\test\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#6 D:\localweb\www\test\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('import', Array)
#7 D:\localweb\www\test\vendor\yiisoft\yii2\web\Application.php(100): yii\base\Module->runAction('podium/install/...', Array)
#8 D:\localweb\www\test\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 D:\localweb\www\test\frontend\web\index.php(17): yii\base\Application->run()
```

**Comment by bizley** [comment]
Thanks for finding the bug! I need to fix it in the next version.
You see this in logs because adding new admin failed from any reason.

As a quick fix you can change [this line](https://github.com/bizley/yii2-podium/blob/0.3.1/src/maintenance/Installation.php#L10) in your `vendor/bizley/podium/src/maintenance/Install.php` file to

```
use yii\base\Exception;
```

It should be fine with this. Still, there must be some other error with saving admin on your side. I've installed fresh Yii 2.0.10 with advanced template on fresh database and everything was ok.

**Comment by xiaobuxun** [comment]
Hi bizley,

Thank you many much, I chang this code like you commend. It is works for me now.

Good work, very nice forum!

Thanks!
